# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FZone' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FZone
pod 'Presentr'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
pod 'SnapKit', '~> 3.2.0'
  target 'FZoneTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
